[package]
name = "ralavest"
version = "2.1.0-unsafe"
edition = "2021"
license = "MIT"
description = "featureless HTTP server library"
repository = "https://github.com/Marfa-Creation/ralavest"

[dependencies]
#TODO: use nom instead of regex
nom = "8.0.0"
percent-encoding = "2.3.1"
regex = "1.11.1"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.42.0", features = ["full"] }
url = "2.5.4"


# debugging purpose
[[bin]]
name = "bin"
path = "src/bin.rs"
